import { useEffect, useState } from 'react';
import { base44 } from '@/api/base44Client';
import { Target, HardHat, Star, ChevronRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import PageHeader from '@/components/shared/PageHeader';
import { JOB_STATUSES } from '@/lib/roles';
import StatusBadge from '@/components/shared/StatusBadge';

export default function MatchCentre() {
  const [jobs, setJobs] = useState([]);
  const [contractors, setContractors] = useState([]);
  const [matches, setMatches] = useState([]);
  const [selectedJob, setSelectedJob] = useState(null);
  const [loading, setLoading] = useState(true);
  const [assigning, setAssigning] = useState(null);

  useEffect(() => {
    Promise.all([
      base44.entities.Job.filter({ archived: false }),
      base44.entities.ContractorProfile.filter({ approval_status: 'approved', archived: false }),
      base44.entities.JobMatch.list('-created_date', 200),
    ]).then(([j, c, m]) => {
      setJobs(j.filter(job => ['ready_to_match', 'offers_sent'].includes(job.status)));
      setContractors(c);
      setMatches(m);
      setLoading(false);
    });
  }, []);

  const selectJob = (job) => {
    setSelectedJob(job);
  };

  const jobMatches = selectedJob ? matches.filter(m => m.job_id === selectedJob.id) : [];
  const jobMatchContractors = jobMatches
    .map(m => ({ match: m, contractor: contractors.find(c => c.id === m.contractor_id) }))
    .filter(x => x.contractor)
    .sort((a, b) => (b.match.match_score || 0) - (a.match.match_score || 0));

  const handleAssign = async (contractorId) => {
    if (!selectedJob) return;
    setAssigning(contractorId);
    await base44.entities.JobAssignment.create({
      job_id: selectedJob.id,
      contractor_id: contractorId,
      assignment_status: 'active',
      assigned_at: new Date().toISOString(),
    });
    await base44.entities.Job.update(selectedJob.id, { status: 'assigned' });
    setJobs(prev => prev.filter(j => j.id !== selectedJob.id));
    setSelectedJob(null);
    setAssigning(null);
  };

  if (loading) return <div className="p-6 animate-pulse space-y-3">{[...Array(4)].map((_, i) => <div key={i} className="h-16 bg-muted rounded-xl" />)}</div>;

  return (
    <div className="p-4 lg:p-6 max-w-7xl mx-auto">
      <PageHeader title="Match Centre" subtitle="Assign contractors to jobs" />

      <div className="grid lg:grid-cols-2 gap-6">
        {/* Jobs awaiting matching */}
        <div className="bg-card border border-border rounded-xl overflow-hidden">
          <div className="px-4 py-3 border-b border-border">
            <h2 className="font-semibold text-sm">Jobs Ready to Match ({jobs.length})</h2>
          </div>
          {jobs.length === 0 ? (
            <div className="py-12 text-center text-sm text-muted-foreground">No jobs awaiting matching</div>
          ) : (
            <div className="divide-y divide-border">
              {jobs.map(job => {
                const s = JOB_STATUSES[job.status];
                return (
                  <button
                    key={job.id}
                    onClick={() => selectJob(job)}
                    className={`w-full flex items-center gap-3 px-4 py-3 text-left transition-colors ${selectedJob?.id === job.id ? 'bg-primary/5 border-l-2 border-l-primary' : 'hover:bg-muted/50'}`}
                  >
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium">{job.title}</p>
                      <p className="text-xs text-muted-foreground">{job.site_postcode} • {job.trade_category || 'Any trade'}</p>
                    </div>
                    {s && <StatusBadge label={s.label} color={s.color} />}
                    <ChevronRight className="w-4 h-4 text-muted-foreground flex-shrink-0" />
                  </button>
                );
              })}
            </div>
          )}
        </div>

        {/* Contractor matches */}
        <div className="bg-card border border-border rounded-xl overflow-hidden">
          <div className="px-4 py-3 border-b border-border">
            <h2 className="font-semibold text-sm">
              {selectedJob ? `Matches for: ${selectedJob.title}` : 'Select a job to see matches'}
            </h2>
          </div>
          {!selectedJob ? (
            <div className="py-12 text-center text-sm text-muted-foreground">
              <Target className="w-8 h-8 mx-auto mb-2 text-muted-foreground/50" />
              Select a job to view matched contractors
            </div>
          ) : jobMatchContractors.length === 0 ? (
            <div className="py-12 text-center text-sm text-muted-foreground">
              <p>No matches yet for this job.</p>
              <p className="mt-1 text-xs">Matches are generated by the matching engine.</p>
            </div>
          ) : (
            <div className="divide-y divide-border">
              {jobMatchContractors.map(({ match, contractor }) => (
                <div key={match.id} className="flex items-center gap-3 px-4 py-3">
                  <div className="w-9 h-9 bg-primary/10 rounded-full flex items-center justify-center flex-shrink-0">
                    <HardHat className="w-4 h-4 text-primary" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium">{contractor.trading_name || contractor.legal_name || 'Unnamed'}</p>
                    <div className="flex items-center gap-1">
                      <Star className="w-3 h-3 text-amber-500" />
                      <span className="text-xs text-muted-foreground">{match.match_score ? `${match.match_score}% match` : 'Unscored'}</span>
                    </div>
                  </div>
                  <Button
                    size="sm"
                    onClick={() => handleAssign(contractor.id)}
                    disabled={assigning === contractor.id}
                    className="text-xs"
                  >
                    {assigning === contractor.id ? 'Assigning...' : 'Assign'}
                  </Button>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}